AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  mangajj-lambda

  SAM Template for mangajj-lambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:
  MangaJJFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: extract-mangajj
      CodeUri: mangajj/
      Handler: app.lambda_handler
      Runtime: python3.7
      AutoPublishAlias: live
      Events:
        MangaJJ:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /chapter
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  MangaJJApi:
    Description: "API Gateway endpoint URL for Prod stage for function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/chapter/"
  MangaJJFunction:
    Description: "MangaJJ Lambda Function ARN"
    Value: !GetAtt MangaJJFunction.Arn
  MangaJJFunctionIamRole:
    Description: "Implicit IAM Role created for MangaJJ function"
    Value: !GetAtt MangaJJFunctionRole.Arn
